#!/bin/bash

## #ddev-generated
## Description: Opens up a fish shell in the container or executs a command within a fish shell
## Usage: fish
## Example: ddev fish
## ExecRaw: true

ddev exec fish "$@"
