#ddev-generated
ahoyapi: v2
commands:
  build:
    usage: 'Tidy up README.md'
    cmd: /var/www/html/.ddev/readme/build.sh

  watch:
    usage: 'Watch README.md for changes'
    cmd: node /var/www/html/.ddev/readme/watch.cjs
